### ISSUE TITLE
The symbolic link doesn't get created

### ISSUE THREAD

**Issue by SamuelCharpentier** [Klustre/cep-svelte-starter#2]
I don't know if this is still working for you but I can't seem to get it to work. 

I'm on Windows 10 and I've followed the instructions on the readme page, using degit, updating the package.json to `set` and `timeout`.

When I run `npm start`, everything seems to compile successfully, but then I open Photoshop or illustrator and I can't see `Svelte Starter` in the extension menu under windows. Am I missing a step or is it the project that's out dated or made to work only on Mac?

**Comment by Klustre** [comment]
Hey, this was never tested on Windows, so you'll have to do some digging as to why it's not working. Have a look if a Symbolic Link is created in the [extensions folder](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#extension-folders). Also check that the [debug flags](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions) are correctly being set.

**Comment by SamuelCharpentier** [comment]
Turns out you need higher privileges on windows to create the symlink (as in admin privileges). I’ve been rewriting cep-bundler-core (which is responsible for said symlink) from the ground up to support all possible options in the manifest and fixing this odd parameter structure and broken symlink.
